
### Nieuwe gebruiker aanmaken
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "Test McTest",
    "password": "SecurePassword"
}

###

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Test McTest",
    "password": "SecurePassword"
}