services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ../shared/Dockerfile.dev
    container_name: api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./api-gateway/.env
      - .env

  user-service:
    build:
      context: ./user-service
      dockerfile: ../shared/Dockerfile.dev
    container_name: user-service
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env
      - .env
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  competition-service:
    build:
      context: ./competition-service
      dockerfile: ../shared/Dockerfile.dev
    container_name: competition-service
    ports:
      - "3002:3002"
    env_file:
      - ./competition-service/.env
      - .env
    volumes:
      - ./competition-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  submission-service:
    build:
      context: ./submission-service
      dockerfile: ../shared/Dockerfile.dev
    container_name: submission-service
    ports:
      - "3003:3003"
    env_file:
      - ./submission-service/.env
      - .env
    volumes:
      - ./submission-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

volumes:
  mongo-data:
