# Dockerfile.dev

FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Install nodemon globally (optional but handy)
RUN npm install -g nodemon

# Copy everything
COPY . .

# Expose port
EXPOSE 3000

# Use nodemon with ts-node to watch and reload on changes
CMD ["nodemon", "--watch", "src", "--exec", "tsx", "src/index.ts"]
